WebApplication1/Models/DataTableResult.cs
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public class DataTableResult<T>
    {
        public int sEcho { get; set; }
        public int iTotalRecords { get; set; }
        public int iTotalDisplayRecords { get; set; }
        public List<T> aaData { get; set; }
    }
}

WebApplication1/Models/Progress/Progress.cs
namespace WebApplication1.Models
{
    public class StudentProgression
    {
        public StudentProgression(long id, string name)
        {
            StudentId = id;
            StudentName = name;
        }

        public long StudentId { get; set; }

        public string StudentName { get; set; }

        public double Progresss { get; set; }

        public double CorrectAnswerRate { get; set; }

        public double NumberOfExercises { get; set; }

        public double DifficultyOfExercises { get; set; }
    }
}

WebApplication1/Models/StudentsModel.cs
using System.Collections.Generic;
using WebApplication1.Data.Entities;

namespace WebApplication1.Models
{
    public class StudentsModel : List<Student>
    {
        public StudentsModel(IEnumerable<Student> collection) : base(collection) { }
    }
}

WebApplication1/Controllers/ProgressionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Data.Contexts;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProgressionController : Controller
    {
        private SnappetContext _context;
        protected SnappetContext Context
        {
            get
            {
                if (_context == null)
                {
                    _context = new SnappetContext();
                }
                return _context;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public List<StudentProgression> GetProgress(DateTime dateStart, DateTime dkateEnd)
        {
            var answers = Context.Answers; //todo: using or at least dispose?
            
            var nrAnswers = answers.Count();
            var nrCorrectanswer = answers.Count(a => a.Correct);
            var nrExercises = answers.Select(x => x.ExerciseId).Distinct().Count();
            var avgDifficulty = answers.Average(a => a.Exercise.Difficulty);
            var avgCorrectnessRate = (double)nrCorrectanswer / nrExercises;
            var avgProgress = answers.Average(x => x.Progress);

            var students = answers.GroupBy(a => a.Student).Select(a => a.Key).ToList();
            var nrOfStudents = students.Count();

            var progressList = new List<StudentProgression>();

            foreach (var student in students)
            {
                var progress = new StudentProgression(student.Id, student.Name);

                progress.NumberOfExercises = answers.Count(a => a.StudentId == student.Id);
                var numOfCorrectExercisesForStudent = answers.Where(a => a.StudentId == student.Id).Count(a => a.Correct);
                progress.CorrectAnswerRate = numOfCorrectExercisesForStudent / progress.NumberOfExercises;
                progress.DifficultyOfExercises = progress.NumberOfExercises > 0 ? answers.Where(a => a.StudentId == student.Id).Average(a => a.Exercise.Difficulty) : 0; //set 0 if no exercises found
                var answersForStudent = answers.Where(a => a.StudentId == student.Id);
                var avgProgressForStudent = answersForStudent.Any() ? answersForStudent.Average(a => a.Progress) : 0;
                progress.Progresss = (avgProgressForStudent - avgProgress) / avgProgress;

                progressList.Add(progress);
            }

            return progressList;
        }
    }
}

WebApplication1/Controllers/StudentsController.cs
using System.Linq;
using System.Web.Mvc;
using WebApplication1.Data.Contexts;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class StudentsController : Controller
    {
        private SnappetContext _context;
        protected SnappetContext Context
        {
            get
            {
                if (_context == null)
                {
                    _context = new SnappetContext();
                }
                return _context;
            }
        }

        //[Route("students")] //todo: annotation routes zijn sjiek later configureren if needed
        public ActionResult Index()
        {
            //todo: add service which gets the data for model? even better would be client js framework to get from REST service
            StudentsModel model = GetStudents();
            return View(model);
        }

        //todo: refactor to service
        private StudentsModel GetStudents()
        {
            var studentList = Context.Students.ToList();
            return new StudentsModel(studentList);
        }
    }
}

WebApplication1/Views/Progression/Index.cshtml
@{
    ViewBag.Title = "Progression Page";
}

<div>
    <h2>Progression</h2>
    <table id="progressList" class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>StudentId</th>
                <th>StudentName</th>
                <th>CorrectAnswerRate</th>
                <th>NumberOfExercises</th>
                <th>DifficultyOfExercises</th>
            </tr>
        </thead>
    </table>
</div>

@Scripts.Render("~/bundles/jquery")

<script>
    $(document).ready(function () {
        var uri = 'api/progress';

        var table = $('#progressList').DataTable({
            bJQueryUI: false,
            bProcessing: true,
            sAjaxSource: uri,
            aoColumnDefs: [{ 'bSortable': false }],
            columns: [
                { "data": "StudentId" },
                { "data": "StudentName" },
                { "data": "CorrectAnswerRate" },
                { "data": "NumberOfExercises" },
                { "data": "DifficultyOfExercises" }
            ]
        });
    });
</script>

WebApplication1/Views/Shared/DisplayTemplates/Student.cshtml
@{
    Layout = null;
}

@model WebApplication1.Data.Entities.Student

<tr>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.AverageProgress</td>
</tr>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SnappetChallenge</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Snappet", "Index", "Progression", new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Today", "Index", "Progression")</li>
                    <li>@Html.ActionLink("Students", "Index", "Students")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Students/Index.cshtml
@{
    ViewBag.Title = "Students Page";
}

@model WebApplication1.Models.StudentsModel

<form action="" method="post">
    <div style="margin:10px;">
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th>Id</th>
                <th>Naam</th>
                <th>Avg process</th>
            </tr>
            @Html.DisplayForModel(Model)
        </table>
    </div>
</form>